import 'recipe.dart';

class RecipeData {
  List<Recipe> getRecipes() {
    return [
      Recipe(
          id: 'r1',
          title: 'chakalaka',
          imageUrl: 'assets/chakalaka.jpeg',
          ingredients: [
            'Tomatoes',
            'Onion',
            '½ green pepper and ½ red pepper',
            'Chilli peppers',
            'salt (optional)',
            'Garlic',
            'Curry powder (optional)',
            '1 can of beans'
          ],
          steps: [
            'Heat oil in a pan or pot.',
            'Fry onion, green and red pepper, then add curry powder.',
            'Add grated carrots and continue to fry.',
            'Now add tomatoes and stir.',
            'add chilli pepper if you are using chilli powder add it on step 7.',
            'cover the pot with lid.',
            'Add 1 tin of baked beans and add garlic.'
          ],
          duration: Duration(minutes: 30),
          complexity: Complexity.Simple,
          cost: 00.0,
          description:
              ' A spicy vegetable relish made with tomatoes, onions, and peppers'),
      Recipe(
          id: 'r2',
          title: 'Boerewors Rolls',
          imageUrl: 'assets/boereworsrolls.jpeg',
          ingredients: [
            'Onion (finely chopped)',
            'Crushed Garlic',
            'Grated carrots',
            'Onion',
            'Olive Oil',
            '200g of tomato pronto',
            'Hot Dog Rolls (Cut Half Way Open)',
            'Baked Beans',
            'Boerewors (Grilled)'
          ],
          steps: [
            'Heat oil in a pot, add onions and fry until soft.',
            'Add garlic, chillies, carrots and cook for 3 min.',
            'Add Tomato Pronto and Aromat Original and simmer for 5 min.',
            'Add baked beans and cook for 3 min.',
            'Cut boerewors into 10 evenly sized pieces.',
            'Fill the hot dog roll with half the chakalaka then boerewors and top with the rest of the chakalaka.'
          ],
          duration: Duration(minutes: 20),
          complexity: Complexity.Simple,
          cost: 00.0,
          description:
              'A sausage served on a bun with tomato sauce and onions.'),
      Recipe(
          id: 'r3',
          title: ' A full house Kota',
          imageUrl: 'assets/kota.jpeg',
          ingredients: [
            '700 g loaves white bread, quartered ',
            'Chakalaka or substitute with acthar',
            'Cabbage (shredded)',
            'Frozen chips or make them from scratch',
            'potato seasoning',
            '4 Eggs',
            'Ham',
            'Cheddar cheese',
            'Minute steak',
            'Russian',
            'Polony'
          ],
          steps: [
            'For the chips, pre-heat the oil in the deep fryer. Fry the chips until golden brown.',
            'Put the fried chips on a baking tray lined with paper towel and sprinkle withSeasonings.',
            'On a flat top pan, heat the oil on a medium heat and fry the steak seasoned with you favourite spices.',
            'Season the fried eggs with Knorr Aromat Original.',
            'Cut the centre of the quarter loaf out, pour in a spoon of the chakalaka.',
            'Add slice of polony and russian follow with chips, ham, steak, cheese and egg.'
          ],
          duration: Duration(minutes: 20),
          complexity: Complexity.Simple,
          cost: 00.0,
          description: 'A hollowed-out bread roll'),
      Recipe(
          id: 'r4',
          title: 'Samoosa / Samosa ',
          imageUrl: 'assets/samosa.jpg',
          ingredients: [
            '500g Minced Beef or Chicken',
            '1½ Onion chopped',
            'Garlic',
            '1 teaspoon Curry Powder',
            'Olive Oil or any oil',
            '½ teaspoon Tumeric',
            'Salt',
            'Chilli Powder'
          ],
          steps: [
            'Cook the mince with the,ginger and garlic, spices and salt.',
            'When almost dry, add the chopped onions and cook until all the liquid has evaporated, stirring often to prevent from forming lumps. ',
            'Add butter and stir through the mixture.',
            'Add the chopped coriander. and allow mince to cool'
          ],
          duration: Duration(minutes: 20),
          complexity: Complexity.Challenging,
          cost: 00.0,
          description: 'A savory pastry filled with minced meat and spices.'),
      Recipe(
          id: 'r5',
          title: 'Nama ya Hlogo',
          imageUrl: 'assets/hlogo.jpeg',
          ingredients: [
            'Half cow head cut in cubed',
            'Onion',
            '2 tomatoes',
            '2tablespoon of paprika',
            'salt',
            'Curry powder (optional)'
          ],
          steps: [
            'Boil your cow head with 250ml of water until it is cooked.',
            'put in your tomatoes in bowl and pour in boiled water and let them sit for 3min.',
            'remove them and peel the tomato skin out and dice and keep aside.',
            'pour cooking oil, and chopped onions let the onion saute until soft and after put in all your spices.',
            'Put in your chopped tomatoes follow by your 100ml water.',
            'Allow the meat to cook on medium heat until the soup has thicken up and ready.'
          ],
          duration: Duration(minutes: 30),
          complexity: Complexity.Simple,
          cost: 00.0,
          description: ' Nama ya hlogo /INHLOKO'),
      Recipe(
          id: 'r6',
          title: 'Cow trotters',
          description: 'Cow trotters recipe',
          imageUrl: 'assets/cowtrotters.jpeg',
          ingredients: [
            'Clean Cow trotters cut into pieces',
            'Chili powder (optional)',
            'Tumeric powder half teaspoon',
            'coriander powder',
            'Salt for taste',
            '1 Onion'
          ],
          steps: [
            'put in the trotters in pot and enough water to cover them.',
            ' if you see that water is not enough and trotters are not yet tender, put in some more boiling water',
            ''
          ],
          duration: Duration(minutes: 130),
          complexity: Complexity.Challenging,
          cost: 0.00),
      Recipe(
          id: 'r7',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r8',
          title: 'Mala and Maotwana(Chkicken feet and intestines)',
          description: 'Chicken feets and intestines',
          imageUrl: 'asstes/mala.jpeg',
          ingredients: [
            '8 clean chicken feet',
            '1 Kg of chicken intestines/mala',
            'half onion or 1 small onion',
            '1 tsp of paprika',
            '1 tsp of chicken spice',
            '2 knorr chicken cubes',
            '1 tsp of tumeric',
            '2 tsp of Curry powder'
          ],
          steps: [' '],
          duration: Duration(minutes: 25),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r9',
          title: 'Chicken liver',
          description: 'Chicken liver',
          imageUrl: 'asstes/cliver.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r10',
          title: 'Beef liver',
          description: 'Tender Beef liver',
          imageUrl: 'asstes/bliver.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r11',
          title: 'Samp and beans',
          description: 'Samp and beans',
          imageUrl: 'asstes/sampb.jpeg',
          ingredients: [
            '500g of samp',
            '500g of beans',
            '1 medium onion chopped',
            '2 gloves of garlic (optional)',
            '2 tomatoes chopped',
            '2 or 3 peeled potatoes cut into into cubes',
            'hot sauce/peri peri sauce'
          ],
          steps: [
            'Rinse the samp and beans and soak overnight in water or do this at least 6 hours before cooking',
            'Drain the water after soaking, place the samp and beans mixture in pot then add water',
            'Allow to simmer and add more water if needed, do this till the samp and beans are soft but still little firm, overall this should take about 40 minutes then set aside',
            'In another pot or take pan heat oil then sauté onion till it is soft, add garlic and curry powder then fry for about minute and half. add chopped tomatoes, water and potatoes then simmer till potatoes are slightly soft',
            'Add the mixture to the samp and beans we cooked, slowly cook them till potatoes, samp and beans are all soft, season with salt',
            'when ready you can serve while is still warm'
          ],
          duration: Duration(minutes: 80),
          complexity: Complexity.Challenging,
          cost: 0.00),
      Recipe(
          id: 'r12',
          title: 'Sugar beans',
          description: 'Sugar beans currry',
          imageUrl: 'asstes/sbeans.jpeg',
          ingredients: [
            '2 cups of dried sugar beans',
            '1 chopped onion',
            '2 chopped tomatoes',
            '1 chopped green pepper',
            '1 grated carrot',
            '2 tsp of curry powder',
            'cooking oil',
            'water',
            'salt'
          ],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r13',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r14',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r15',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r16',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r17',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r18',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r19',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r20',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r21',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r22',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r23',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r24',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r25',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r26',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r27',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r28',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r29',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r30',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r31',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r32',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r33',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r34',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r35',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r36',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r37',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r36',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r37',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r38',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r39',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r40',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r41',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r42',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r41',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r42',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r43',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r44',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r45',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r46',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r47',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r48',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r49',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r50',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'asstes/beefstew.jpeg',
          ingredients: [' '],
          steps: [' '],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
    ];
  }
}
