import 'recipe.dart';

class RecipeData {
  List<Recipe> getRecipes() {
    return [
      Recipe(
          id: 'r1',
          title: 'chakalaka',
          imageUrl: 'assets/chakalaka.jpeg',
          ingredients: [
            'Tomatoes',
            'Onion',
            '½ green pepper and ½ red pepper',
            'Chilli peppers',
            'salt (optional)',
            'Garlic',
            'Curry powder (optional)',
            '1 can of beans'
          ],
          steps: [
            'Heat oil in a pan or pot.',
            'Fry onion, green and red pepper, then add curry powder.',
            'Add grated carrots and continue to fry.',
            'Now add tomatoes and stir.',
            'add chilli pepper if you are using chilli powder add it on step 7.',
            'cover the pot with lid.',
            'Add 1 tin of baked beans and add garlic.'
          ],
          duration: Duration(minutes: 30),
          complexity: Complexity.Simple,
          cost: 00.0,
          description:
              ' A spicy vegetable relish made with tomatoes, onions, and peppers'),
      Recipe(
          id: 'r2',
          title: 'Boerewors Rolls',
          imageUrl: 'assets/boereworsrolls.jpeg',
          ingredients: [
            'Onion (finely chopped)',
            'Crushed Garlic',
            'Grated carrots',
            'Olive Oil',
            '200g of tomato pronto',
            'Hot Dog Rolls (Cut Half Way Open)',
            'Baked Beans',
            'Boerewors (Grilled)'
          ],
          steps: [
            'Heat oil in a pot, add onions and fry until soft.',
            'Add garlic, chillies, carrots and cook for 3 min.',
            'Add Tomato Pronto and Aromat Original and simmer for 5 min.',
            'Add baked beans and cook for 3 min.',
            'Cut boerewors into 10 evenly sized pieces.',
            'Fill the hot dog roll with half the chakalaka then boerewors and top with the rest of the chakalaka.'
          ],
          duration: Duration(minutes: 20),
          complexity: Complexity.Simple,
          cost: 00.0,
          description:
              'A sausage served on a bun with tomato sauce and onions.'),
      Recipe(
          id: 'r3',
          title: ' A fully loaded Kota',
          imageUrl: 'assets/kota.jpeg',
          ingredients: [
            '4 large bread rolls, preferably with a thick crust',
            '1/2 cup vegetable oil',
            '1 onion, finely chopped',
            '1 green pepper, finely chopped',
            '2 cloves garlic, minced',
            '1 lb(500g). polony, sliced',
            '1/2 lb (500g). Russian sausage, sliced',
            '1/2 lb(500g). ham, sliced',
            '1 cup grated cheddar cheese',
            '1 cup French fries, cooked',
            '1/2 cup atchar (pickle relish) or chakalaka',
            '4 beef patties, cooked',
            '4 fish fillets, cooked',
            'Lettuce leaves',
            'Tomato slices',
            'Mayonnaise',
            'Salt and pepper, to taste'
          ],
          steps: [
            'Cut a circle in the top of each bread roll and hollow out the inside, leaving about a 1/2-inch layer of bread around the edges. Set aside.',
            'Heat the oil in a large skillet over medium-high heat.',
            'Add the onion, green pepper, and garlic to the skillet and cook until softened, about 3-4 minutes.',
            'Add the polony, Russian sausage, and ham to the skillet and cook until lightly browned and heated through, about 2-3 minutes.',
            'Spoon the polony, Russian sausage, and ham mixture into the hollowed-out bread rolls, filling them about 1/2 of the way full.',
            'Top the meat mixture in each roll with a layer of French fries.',
            'Add a spoonful of atchar to each roll.',
            'Place a cooked beef patty and a cooked fish fillet on top of the fries and atchar.',
            'Sprinkle a generous amount of grated cheddar cheese over the top of each roll.',
            'Add a few lettuce leaves and a couple of tomato slices to each roll.',
            'Spread some mayonnaise on the inside of the bread tops, and place them back onto the filled rolls.',
            'Serve immediately and enjoy your fully loaded South African kota!',
          ],
          duration: Duration(minutes: 20),
          complexity: Complexity.Simple,
          cost: 00.0,
          description: 'A hollowed-out bread roll'),
      Recipe(
          id: 'r4',
          title: 'Samoosa',
          imageUrl: 'assets/samosa.jpg',
          ingredients: [
            '500g Minced Beef, lamb or Chicken',
            '1½ Onion chopped',
            '2 teaspoons garlic paste',
            '2 teaspoons ginger paste',
            '2 teaspoons cumin powder',
            '½ teaspoon Tumeric',
            '2 teaspoons coriander powder',
            '1 teaspoon garam masala powder',
            '1 teaspoon chili powder',
            'Salt, to taste',
            '2 tablespoons of olive oil',
            '1 cup frozen peas',
            'BELOW IS FOR PASTRY'
                '2 cups all-purpose flour',
            '½ teaspoon salt',
            '2 tablespoons of olive oil',
            '½ cup lukewarm water'
          ],
          steps: [
            'For the filling, heat 2 tablespoons of oil in a large frying pan over medium heat. Add the onions, garlic paste, and ginger paste and cook until the onions are soft and translucent.',
            'Add the minced meat to the pan and cook until browned, breaking it up with a spatula as it cooks.',
            'Add the cumin powder, coriander powder, turmeric powder, garam masala powder, chili powder, and salt to the pan and stir well.',
            'Cook for another 5-7 minutes until the meat is cooked through.',
            'Stir in the frozen peas and fresh coriander and cook for another minute until the peas are heated through. Remove from heat and let the filling cool.',
            'For the pastry, mix together the flour and salt in a large bowl. Add the olive oil and rub it into the flour with your fingertips until the mixture resembles breadcrumbs.',
            'Add the lukewarm water, a little at a time, and knead until the dough is smooth and elastic.',
            'Divide the dough into 10-12 equal pieces and roll each one into a ball.',
            'Roll each ball out into a thin circle, then cut it in half to form two semi-circles.',
            'Take one semi-circle and form it into a cone shape by bringing the two straight edges together and pinching them to seal.',
            'Fill the cone with the meat filling, leaving a little space at the top.',
            'Wet the edges of the pastry with a little water and press them together to seal the samoosa.',
            'Heat vegetable oil in a deep frying pan or a pot over medium heat. Fry the samoosas in batches until they are golden brown and crispy.',
            'Drain the fried samoosas on a paper towel to remove excess oil.',
            'Enjoy your delicious Samoosas!'
          ],
          duration: Duration(minutes: 25),
          complexity: Complexity.Challenging,
          cost: 00.0,
          description: 'A savory pastry filled with minced meat and spices.'),
      Recipe(
          id: 'r5',
          title: 'Nama ya Hlogo',
          imageUrl: 'assets/hlogo.jpeg',
          ingredients: [
            'Half cow head cut in cubed',
            'Onion',
            '2 tomatoes',
            '2tablespoon of paprika',
            'salt',
            'Curry powder (optional)'
          ],
          steps: [
            'Boil your cow head with 250ml of water until it is cooked.',
            'put in your tomatoes in bowl and pour in boiled water and let them sit for 3min.',
            'remove them and peel the tomato skin out and dice and keep aside.',
            'pour cooking oil, and chopped onions let the onion saute until soft and after put in all your spices.',
            'Put in your chopped tomatoes follow by your 100ml water.',
            'Allow the meat to cook on medium heat until the soup has thicken up and ready.'
          ],
          duration: Duration(minutes: 120),
          complexity: Complexity.Challenging,
          cost: 00.0,
          description: ' Nama ya hlogo /INHLOKO'),
      Recipe(
          id: 'r6',
          title: 'Beef trotters',
          description: 'Cow trotters recipe',
          imageUrl: 'assets/dihlako.jpeg',
          ingredients: [
            'Clean Cow trotters cut into pieces',
            '1 onion, chopped',
            '2-3 cloves garlic, minced',
            '1 inch piece of ginger, grated',
            '2-3 tablespoons vegetable oil',
            '1 tablespoon tomato paste',
            '1 teaspoon paprika',
            '1 teaspoon cumin',
            '1 teaspoon coriander',
            '1 teaspoon turmeric',
            'Salt and black pepper to taste',
            '2-3 cups water',
            'Fresh cilantro or parsley, chopped for garnish'
          ],
          steps: [
            'In a large pot, heat the vegetable oil over medium heat.',
            'Add the chopped onion and sauté until it is soft and translucent.',
            'Add the minced garlic and grated ginger and sauté for another minute.',
            'Add the cow trotters to the pot and cook for about 10-15 minutes until they are browned on all sides.',
            'Add the tomato paste, paprika, cumin, coriander, turmeric, salt, and black pepper to the pot and stir well.',
            'Pour in enough water to cover the trotters, bring to a boil, and then reduce the heat to a simmer.',
            'Cover the pot and let the stew simmer for 2-3 hours, or until the trotters are tender and the sauce has thickened.',
            'Serve the Cow Trotters hot, garnished with chopped cilantro or parsley.',
            'Note: Cow Trotters require a long cooking time in order to become tender, so be sure to plan accordingly. This dish is often served with rice, pap (a South African porridge made from cornmeal), or bread to soak up the flavorful sauce.'
          ],
          duration: Duration(minutes: 140),
          complexity: Complexity.Challenging,
          cost: 0.00),
      Recipe(
          id: 'r7',
          title: 'Beef Stew',
          description: 'Tender Beef stew',
          imageUrl: 'assets/beefstew.jpg',
          ingredients: [
            '2 pounds beef chuck or stew meat, cut into 1-inch cubes',
            '2 tablespoons all-purpose flour',
            '1 teaspoon salt',
            '1/2 teaspoon black pepper',
            '2 tablespoons vegetable oil',
            '1 onion, chopped',
            '3 garlic cloves, minced',
            '2 cups beef broth',
            '2 cups water',
            '2 bay leaves',
            '1 tablespoon Worcestershire sauce',
            '1 tablespoon tomato paste',
            '4-5 medium potatoes, peeled and cut into chunks',
            '4-5 medium carrots, peeled and cut into chunks',
            '1 cup frozen peas (optional)'
          ],
          steps: [
            'In a large bowl, toss the beef cubes with the flour, salt, and pepper until evenly coated.',
            'In a large Dutch oven or heavy pot, heat the vegetable oil over medium-high heat.',
            'Add the beef cubes to the pot and cook, stirring occasionally, until they are browned on all sides.',
            'Add the chopped onion and minced garlic to the pot and sauté until the onion is soft and translucent.',
            'Pour in the beef broth, water, bay leaves, Worcestershire sauce, and tomato paste, and stir well to combine.',
            'Bring the stew to a boil, then reduce the heat to a simmer and cover the pot.',
            'Let the stew simmer for about 1 1/2 to 2 hours, stirring occasionally, until the beef is tender and the sauce has thickened.',
            'Add the potato and carrot chunks to the pot and continue simmering until the vegetables are tender, about 30-40 minutes.',
            'If using frozen peas, add them to the pot during the last 5-10 minutes of cooking.',
            'Remove the bay leaves from the stew and serve hot, garnished with chopped fresh parsley or thyme if desired.',
            'Note: This beef stew can also be made in a slow cooker. Simply brown the beef and sauté the onion and garlic in a separate pan, then transfer everything to the slow cooker along with the remaining ingredients. Cook on low for 8-10 hours or on high for 4-6 hours, until the beef and vegetables are tender.'
          ],
          duration: Duration(minutes: 120),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r8',
          title: 'Chicken Feet and Intestine Stew',
          description: 'dish that combines chicken feet and intestines.',
          imageUrl: 'assets/mala.jpeg',
          ingredients: [
            '1 kg chicken feet, cleaned and trimmed',
            '500 g chicken intestines, cleaned and trimmed',
            '1 onion, chopped',
            '2 garlic cloves, minced',
            '1 green bell pepper, chopped',
            '1 red bell pepper, chopped',
            '2 tablespoons olive oil',
            '1 tablespoon paprika',
            ' 1 teaspoon dried thyme',
            '1 teaspoon salt',
            '1/2 teaspoon black pepper',
            '1 can of tomato and onion mix',
            '2 cups water',
            '1 tablespoon cornstarch',
            '1/4 cup water'
          ],
          steps: [
            'Rinse the chicken feet and intestines under cold running water and pat them dry with paper towels.',
            'Cut the chicken feet into small pieces with a sharp knife or kitchen scissors. Cut the intestines into bite-sized pieces.',
            'Heat the olive oil in a large pot over medium-high heat. Add the onion and garlic, and sauté for 2-3 minutes until softened.',
            'Add the green and red bell pepper to the pot and sauté for another 2-3 minutes.',
            'Add the chicken feet and intestines to the pot and sauté for 3-4 minutes until browned on all sides.',
            'Add the paprika, thyme, salt, and black pepper to the pot and stir to combine.',
            'Pour in the can of tomato and onion mix and water. Bring the mixture to a boil, then reduce the heat to low and let it simmer for 45-60 minutes until the chicken feet and intestines are tender.',
            'In a small bowl, whisk together the cornstarch and 1/4 cup water to make a slurry.',
            'Stir the slurry into the pot and let the stew simmer for an additional 5-10 minutes until the sauce has thickened.',
            'Serve the Chicken Feet and Intestine Stew hot, with rice or pap on the side.'
          ],
          duration: Duration(minutes: 25),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r9',
          title: 'Chicken liver',
          description:
              'Chicken livers marinated in peri peri sauce and pan-fried until crispy',
          imageUrl: 'assets/cliver.jpg',
          ingredients: [
            '500g chicken livers, trimmed',
            '2 tablespoons olive oil',
            '1 onion, chopped',
            '2 garlic cloves, minced',
            '1 red bell pepper, chopped',
            '1 tablespoon paprika',
            '1 teaspoon dried oregano',
            '1 teaspoon dried thyme',
            '1 teaspoon salt',
            '1/2 teaspoon black pepper',
            '1/2 cup peri peri sauce',
            '1/4 cup chicken stock',
            'Juice of 1 lemon '
          ],
          steps: [
            'Rinse the chicken livers under cold running water, and pat dry with paper towels. Cut them into bite-sized pieces.',
            'Heat the olive oil in a large skillet over medium-high heat. Add the onion and garlic, and sauté for 2-3 minutes until softened.',
            'Add the chopped red bell pepper to the skillet and sauté for another 2-3 minutes.',
            'Add the chicken livers to the skillet and sauté for 3-4 minutes until browned on all sides.',
            'Add the paprika, oregano, thyme, salt, and black pepper to the skillet and stir to combine.',
            'Add the peri peri sauce and chicken stock to the skillet and stir to coat the chicken livers. Bring the mixture to a simmer, then reduce the heat to low and let it cook for 10-15 minutes until the chicken livers are cooked through.',
            'Stir in the lemon juice and cook for an additional minute.',
            'Serve the Chicken Liver Peri Peri hot with rice, bread, or as a snack.'
          ],
          duration: Duration(minutes: 20),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r10',
          title: 'Beef liver',
          description: 'a tasty beef liver dish',
          imageUrl: 'assets/bliver.jpg',
          ingredients: [
            '500g beef liver, sliced',
            '2 onions, chopped',
            '2 garlic cloves, minced',
            '1 red bell pepper, chopped',
            '1 green bell pepper, chopped',
            '2 tablespoons vegetable oil or olive oil',
            '2 tablespoons tomato paste',
            '1 tablespoon curry powder',
            '1 teaspoon paprika',
            '1 teaspoon salt',
            '1/2 teaspoon black pepper',
            '1/2 cup beef stock'
          ],
          steps: [
            'Rinse the beef liver slices under cold running water and pat them dry with paper towels.',
            'In a large skillet or frying pan, heat the vegetable oil over medium-high heat. Add the sliced beef liver to the pan and sauté for 2-3 minutes until browned on both sides.',
            'Remove the beef liver from the pan and set aside on a plate.',
            'In the same pan, sauté the chopped onions, garlic, red and green bell peppers for 2-3 minutes until softened.',
            'Add the tomato paste, curry powder, paprika, salt, and black pepper to the pan and stir to combine.',
            'Pour in the beef stock and stir to combine. Bring the mixture to a simmer.',
            'Return the beef liver to the pan and let it simmer in the sauce for 5-7 minutes until cooked through and tender.',
            'Serve the beef liver hot with a side of your choice, such as rice, pap, or roasted vegetables.'
          ],
          duration: Duration(minutes: 20),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r11',
          title: 'Samp and beans',
          description: 'Samp and beans',
          imageUrl: 'assets/samob.jpeg',
          ingredients: [
            '500g of samp',
            '500g of beans',
            '1 medium onion chopped',
            '2 gloves of garlic (optional)',
            '2 tomatoes chopped',
            '2 or 3 peeled potatoes cut into into cubes',
            'hot sauce/peri peri sauce'
          ],
          steps: [
            'Rinse the samp and beans and soak overnight in water or do this at least 6 hours before cooking',
            'Drain the water after soaking, place the samp and beans mixture in pot then add water',
            'Allow to simmer and add more water if needed, do this till the samp and beans are soft but still little firm, overall this should take about 40 minutes then set aside',
            'In another pot or take pan heat oil then sauté onion till it is soft, add garlic and curry powder then fry for about minute and half. add chopped tomatoes, water and potatoes then simmer till potatoes are slightly soft',
            'Add the mixture to the samp and beans we cooked, slowly cook them till potatoes, samp and beans are all soft, season with salt',
            'when ready you can serve while is still warm'
          ],
          duration: Duration(minutes: 80),
          complexity: Complexity.Challenging,
          cost: 0.00),
      Recipe(
          id: 'r12',
          title: 'Sugar beans',
          description:
              'a delicious and hearty dish made with red speckled sugar beans',
          imageUrl: 'assets/sbeans.jpeg',
          ingredients: [
            '1 cup red speckled sugar beans, soaked overnight and drained',
            '2 tablespoons vegetable oil',
            '1 onion, chopped',
            '2 cloves garlic, minced',
            '1 red bell pepper, chopped',
            '1 teaspoon ground cumin',
            '1 teaspoon ground coriander',
            '1 teaspoon smoked paprika',
            '1 teaspoon dried oregano',
            '1 teaspoon salt',
            '1/2 teaspoon black pepper',
            '2 cups vegetable or chicken broth',
            '1 can (14 ounces) diced tomatoes, undrained',
            'Chopped fresh parsley, for garnish (optional)'
          ],
          steps: [
            'Heat the vegetable oil in a large pot over medium-high heat.',
            'Add the chopped onion, minced garlic, and chopped red bell pepper to the pot and sauté until the vegetables are soft and the onion is translucent.',
            'Add the soaked and drained red speckled sugar beans to the pot and stir well to combine.,'
                'Add the ground cumin, ground coriander, smoked paprika, dried oregano, salt, and black pepper to the pot, and stir well to coat the beans and vegetables with the spices.',
            'Pour in the vegetable or chicken broth and the undrained diced tomatoes, and stir well to combine.',
            'Bring the mixture to a boil, then reduce the heat to low and cover the pot with a lid.',
            'Let the mixture simmer for about 1 1/2 to 2 hours, stirring occasionally, until the beans are tender and the sauce has thickened.',
            'Serve hot, garnished with chopped fresh parsley if desired.',
            'Note: You can also add other vegetables such as chopped carrots or celery to the pot for added flavor and nutrition.'
          ],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r13',
          title: 'Chicken Peri-Peri',
          description:
              'A spicy grilled chicken dish marinated in peri-peri sauce',
          imageUrl: 'assets/periperichicken.jpeg',
          ingredients: [
            '4-6 chicken thighs or drumsticks',
            '1/4 cup olive oil',
            '2 tablespoons lemon juice',
            '4 cloves garlic, minced',
            '1 tablespoon paprika',
            '1 tablespoon smoked paprika',
            '1 tablespoon dried oregano',
            '1 tablespoon dried thyme',
            '1 tablespoon dried basil',
            '1 tablespoon chili flakes',
            '1 tablespoon salt',
            '1 tablespoon black pepper',
            '2-3 fresh red chilies, chopped',
            '2 tablespoons red wine vinegar',
            '1 tablespoon honey'
          ],
          steps: [
            'In a large bowl, mix together the olive oil, lemon juice, garlic, paprika, smoked paprika, oregano, thyme, basil, chili flakes, salt, and black pepper.',
            'Add the chicken to the bowl and toss to coat with the marinade.',
            'Cover the bowl with plastic wrap and refrigerate for at least 2 hours or overnight.',
            'Preheat the grill to medium-high heat.',
            'Remove the chicken from the marinade and grill for 6-8 minutes per side or until cooked through.',
            'In a small saucepan, combine the chopped chilies, red wine vinegar, and honey. Heat over low heat, stirring occasionally, until the honey has melted and the sauce is heated through.',
            'Serve the grilled chicken with the peri-peri sauce on the side for dipping.'
          ],
          duration: Duration(minutes: 16),
          complexity: Complexity.Challenging,
          cost: 0.00),
      Recipe(
          id: 'r14',
          title: 'Chutney Chicken',
          description: 'A sweet and spicy chicken dish made with chutney',
          imageUrl: 'assets/chutneychick.jpg',
          ingredients: [
            '4-6 chicken thighs or drumsticks',
            '1/2 cup chutney',
            '1/4 cup mayonnaise',
            '1 tablespoon soy sauce',
            '1 tablespoon lemon juice',
            '2 cloves garlic, minced',
            '1 teaspoon curry powder',
            '1/2 teaspoon ground cumin',
            '1/2 teaspoon ground coriander',
            'Salt and black pepper, to taste'
          ],
          steps: [
            'Preheat the oven to 200°C (400°F).',
            'In a large bowl, mix together the chutney, mayonnaise, soy sauce, lemon juice, garlic, curry powder, cumin, coriander, salt, and black pepper.',
            'Add the chicken to the bowl and toss to coat with the marinade.',
            'Arrange the chicken pieces in a single layer in a baking dish.',
            'Bake the chicken for 40-45 minutes, or until the chicken is cooked through and the skin is crispy.',
            'Serve hot with rice or your preferred side dish.'
          ],
          duration: Duration(minutes: 45),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r15',
          title: 'Lamb Curry',
          description: 'A spicy curry made with lamb and vegetables.',
          imageUrl: 'assets/LambCurry.jpg',
          ingredients: [
            '1 kg lamb shoulder or leg, cut into bite-sized pieces'
                '2 onions, chopped',
            '4 garlic cloves, minced',
            '2 tablespoons ginger, grated',
            '2 tomatoes, chopped',
            '2 tablespoons tomato paste',
            '1 tablespoon cumin seeds',
            '1 tablespoon coriander seeds',
            '1 teaspoon turmeric',
            '1 teaspoon chili powder',
            '1 cinnamon stick',
            '4 cardamom pods',
            '4 cloves',
            '2 bay leaves',
            '2 tablespoons olive oil',
            '2 cups water',
            'Salt and black pepper, to taste',
            'Fresh coriander, for garnish'
          ],
          steps: [
            'In a large pot, heat the olive oil over medium heat. Add the onions and sauté until they are soft and translucent.',
            'Add the garlic, ginger, cumin seeds, coriander seeds, turmeric, chili powder, cinnamon stick, cardamom pods, cloves, and bay leaves to the pot. Cook for 1-2 minutes or until fragrant.',
            'Add the lamb pieces to the pot and stir to coat them with the spices. Cook until the lamb is browned on all sides.',
            'Add the chopped tomatoes, tomato paste, and water to the pot. Stir well and bring the mixture to a boil.',
            'Reduce the heat to low and let the curry simmer for about 1-2 hours or until the lamb is tender and the sauce has thickened.',
            'Season with salt and black pepper to taste. Garnish with fresh coriander and serve hot with rice or your preferred side dish.'
          ],
          duration: Duration(minutes: 90),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r16',
          title: 'Vetkoek and Mince',
          description: 'Tender Beef stew',
          imageUrl: 'assets/vmince.jpeg',
          ingredients: [
            '4 cups all-purpose flour',
            '2 tablespoons sugar',
            '1 teaspoon salt',
            '2 tablespoons instant yeast',
            '1 cup lukewarm water',
            'oil for frying',
            '500g minced beef or lamb',
            '2 onions, chopped',
            '2 garlic cloves, minced',
            '2 tomatoes, chopped',
            '2 tablespoons tomato paste',
            '1 teaspoon ground cumin',
            '1 teaspoon ground coriander',
            '1 teaspoon paprika',
            '1/2 teaspoon dried thyme',
            'Salt and black pepper, to taste',
          ],
          steps: [
            'Instructions for Vetkoek :'
                'In a large bowl, mix together the flour, sugar, salt, and instant yeast.',
            'Add the lukewarm water to the bowl and mix until a dough forms.',
            'Knead the dough for 10-15 minutes or until it becomes smooth and elastic.',
            'Cover the bowl with a damp cloth and let the dough rise in a warm place for 1 hour or until it has doubled in size.',
            'Heat the vegetable oil in a large frying pan or pot.',
            'Divide the dough into 12-16 equal pieces and shape them into rounds or oval shapes.',
            'Fry the dough in the hot oil, flipping them over occasionally, until they are golden brown and cooked through. Remove from the oil and place them on paper towels to drain off excess oil.',
            'Instructions for Mince filling:',
            'In a large frying pan or pot, heat some vegetable oil over medium heat.',
            'Add the chopped onions and sauté until they are soft and translucent.',
            'Add the minced beef or lamb to the pan and cook until it is browned on all sides.',
            'Add the garlic, chopped tomatoes, tomato paste, ground cumin, ground coriander, paprika, dried thyme, salt, and black pepper to the pan. Stir well and cook for 10-15 minutes or until the sauce has thickened and the meat is cooked through.',
            'Serve the mince filling inside the Vetkoek, sliced in half.'
          ],
          duration: Duration(minutes: 50),
          complexity: Complexity.Challenging,
          cost: 0.00),
      Recipe(
          id: 'r17 ',
          title: 'Braaied Chicken Intestines',
          description: 'Mala',
          imageUrl: 'assets/amala.jpg',
          ingredients: [
            '500g chicken intestines, cleaned and rinsed',
            '1/4 cup olive oil',
            '2 tablespoons paprika',
            '1 tablespoon dried oregano',
            '1 teaspoon salt',
            '1/2 teaspoon black pepper',
            'lemon Juice or lemon',
            'Wooden skewers, soaked in water for at least 30 minutes',
          ],
          steps: [
            'Rinse the chicken intestines under cold running water and pat them dry with paper towels.',
            'Cut the chicken intestines into 5-6 inch long pieces, and thread them onto the soaked wooden skewers, leaving some space between each piece.',
            'In a small bowl, whisk together the olive oil, paprika, oregano, salt, and black pepper.',
            ' Brush the marinade over the chicken intestines, coating them evenly.',
            'Preheat a barbecue grill or grill pan to medium-high heat.',
            'Place the skewers of chicken intestines onto the grill and cook for 4-5 minutes per side, or until browned and crispy.',
            'Remove the skewers from the grill and place them on a platter.',
            'Squeeze fresh lemon juice over the Braaied Chicken Intestines and serve them hot.'
          ],
          duration: Duration(minutes: 20),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r18',
          title: 'Chana Masala',
          description:
              'a spicy vegetarian dish made with chickpeas cooked in a tomato-based sauce with a blend of spices.',
          imageUrl: 'assets/masala.jpg',
          ingredients: [
            '2 cans of chickpeas, drained and rinsed',
            '2 tablespoons vegetable oil',
            '1 large onion, finely chopped',
            '3 garlic cloves, minced',
            '1 tablespoon grated fresh ginger',
            '1 teaspoon ground cumin',
            '1 teaspoon ground coriander',
            '1/2 teaspoon ground turmeric',
            '1/4 teaspoon cayenne pepper (optional)',
            '1 can of diced tomatoes',
            '1/2 cup water',
            'Salt, to taste',
            'Fresh cilantro, chopped for garnish'
          ],
          steps: [
            'Heat oil in a large pan over medium heat. Add the onions and cook until they are soft and translucent, about 5-7 minutes.',
            'Add the garlic and ginger and cook for an additional 1-2 minutes.',
            'Add the ground cumin, coriander, turmeric, and cayenne pepper (if using) to the pan and cook for 1 minute, stirring constantly to prevent burning.',
            'Add the diced tomatoes and water to the pan and bring to a simmer.',
            'Add the chickpeas to the pan and stir well to combine with the tomato mixture.',
            'Simmer the chickpeas in the tomato mixture for 10-15 minutes or until the sauce has thickened and the chickpeas are heated through.',
            'Add salt to taste and garnish with chopped cilantro.',
            'Serve hot with rice or naan bread.'
          ],
          duration: Duration(minutes: 30),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r19',
          title: 'Gizzards and Pap',
          description:
              'Cooked chicken gizzards served with pap (a type of porridge made from maize meal) and a spicy tomato relish',
          imageUrl: 'assets/gpap.jpeg',
          ingredients: [
            '500g chicken gizzards, cleaned and trimmed',
            '1 onion, chopped',
            '2 garlic cloves, minced',
            '1 green bell pepper, chopped',
            '1 red bell pepper, chopped',
            '2 tablespoons olive oil',
            '1 tablespoon paprika',
            '1 teaspoon dried thyme',
            '1 teaspoon salt',
            '1/2 teaspoon black pepper',
            '1 can of tomato and onion mix',
            '2 cups water',
            '1 cup maize meal'
          ],
          steps: [
            'Rinse the chicken gizzards under cold running water and pat them dry with paper towels. Cut them into bite-sized pieces.',
            'Heat the olive oil in a large pot over medium-high heat. Add the onion and garlic, and sauté for 2-3 minutes until softened.',
            'Add the green and red bell pepper to the pot and sauté for another 2-3 minutes.',
            'Add the chicken gizzards to the pot and sauté for 3-4 minutes until browned on all sides.',
            'Add the paprika, thyme, salt, and black pepper to the pot and stir to combine.',
            'Pour in the can of tomato and onion mix and water. Bring the mixture to a boil, then reduce the heat to low and let it simmer for 45-60 minutes until the gizzards are tender.',
            'While the gizzards are cooking, prepare the pap. In a separate pot, bring 4 cups of water to a boil. Slowly pour in the maize meal, stirring constantly to prevent lumps from forming. Reduce the heat to low and let the mixture simmer for 20-30 minutes until it thickens and forms a porridge-like consistency.',
            'Serve the gizzards and pap hot, with the pap spooned onto plates and the gizzards placed on top.'
          ],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r20',
          title: 'Mogodu/ tribe',
          description:
              'a traditional South African dish made with beef tripe and intestines in a spicy tomato-based sauce',
          imageUrl: 'assets/mogodu.jpeg',
          ingredients: [
            '500g beef tripe, cleaned and chopped',
            '500g beef intestines, cleaned and chopped',
            '1 onion, chopped',
            '2 garlic cloves, minced',
            '1 green bell pepper, chopped',
            '1 red bell pepper, chopped',
            '2 tablespoons vegetable oil',
            '2 tablespoons tomato paste',
            '2 tablespoons curry powder',
            '1 teaspoon cumin',
            '1 teaspoon paprika',
            '1 teaspoon salt',
            '1/2 teaspoon black pepper',
            '2 cups beef stock',
            '1 can diced tomatoes',
            '1 bay leaf'
          ],
          steps: [
            'Rinse the beef tripe and intestines under cold running water and chop them into bite-sized pieces.',
            'In a large pot, heat the vegetable oil over medium-high heat. Add the chopped onion and garlic, and sauté for 2-3 minutes until softened.',
            'Add the green and red bell pepper to the pot and sauté for another 2-3 minutes.',
            'Add the chopped beef tripe and intestines to the pot and sauté for 5-7 minutes until browned on all sides.',
            'Add the tomato paste, curry powder, cumin, paprika, salt, and black pepper to the pot and stir to combine.',
            'Pour in the beef stock and diced tomatoes. Add the bay leaf to the pot.',
            'Bring the mixture to a boil, then reduce the heat to low and let it simmer for 2-3 hours until the tripe and intestines are tender and the sauce has thickened.',
            'Serve the Mala Mogodu hot, with pap, bread, or rice on the side.'
          ],
          duration: Duration(minutes: 180),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r21',
          title: 'Creamy Garlic Pasta',
          description: 'Tasty creamy garlic pasta',
          imageUrl: 'assets/pasta.jpg',
          ingredients: [
            '1 pound of pasta (your choice of shape)',
            '4 cloves of garlic, minced',
            '2 tablespoons of butter',
            '2 tablespoons of all-purpose flour',
            '2 cups of milk',
            '1/2 cup of grated parmesan cheese',
            'Salt and pepper to taste',
            'Chopped fresh parsley for garnish (optional)'
          ],
          steps: [
            'Cook the pasta according to the package instructions until al dente. Drain and set aside.',
            'In a large saucepan over medium heat, melt the butter and sauté the garlic until fragrant, about 1-2 minutes.',
            'Sprinkle the flour over the butter and garlic, whisking constantly for 1-2 minutes until the mixture is smooth and bubbly.',
            'Gradually whisk in the milk, stirring constantly to prevent lumps from forming. Cook for 5-7 minutes until the sauce has thickened and coats the back of a spoon.',
            'Stir in the grated parmesan cheese until melted and smooth. Season with salt and pepper to taste.',
            'Add the cooked pasta to the saucepan and toss to coat in the creamy sauce.',
            'Serve hot, garnished with chopped parsley if desired.'
          ],
          duration: Duration(minutes: 30),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r22',
          title: 'Noodles',
          description: 'Stir-Fried Noodles with Vegetables and Chicken',
          imageUrl: 'assets/noodles.jpg',
          ingredients: [
            '8 oz. dried noodles (such as egg noodles or spaghetti)',
            '2 tbsp vegetable oil',
            '1 small onion, thinly sliced',
            '2 garlic cloves, minced',
            '1 red bell pepper, thinly sliced',
            '1 cup of shredded carrots',
            '2 cups of cooked chicken, shredded or diced (optional)',
            '2 tbsp soy sauce',
            '1 tbsp oyster sauce (optional)',
            'Salt and pepper to taste',
            'Chopped scallions and sesame seeds for garnish'
          ],
          steps: [
            'Cook the noodles according to package instructions until al dente. Drain and set aside.',
            'In a large wok or skillet, heat the oil over high heat. Add the onion and garlic and stir-fry for 1-2 minutes until fragrant.',
            'Add the red bell pepper and shredded carrots and continue stir-frying for another 2-3 minutes until the vegetables are tender-crisp.',
            'Add the cooked chicken (if using) and stir to combine.',
            'Add the cooked noodles to the wok or skillet and stir-fry for 1-2 minutes until the noodles are heated through.',
            'Drizzle the soy sauce and oyster sauce over the noodles and vegetables, tossing to combine. Season with salt and pepper to taste.',
            'Serve hot, garnished with chopped scallions and sesame seeds.'
          ],
          duration: Duration(minutes: 25),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r23',
          title: 'Creamy Spinach',
          description: 'delicious and easy-to-make creamy spinach recipe',
          imageUrl: 'assets/spinach.png',
          ingredients: [
            '1 pound fresh spinach, washed and trimmed',
            '2 tbsp unsalted butter',
            '2 garlic cloves, minced',
            '1/2 cup heavy cream',
            '1/4 cup grated parmesan cheese',
            'Salt and pepper to taste',
            'Pinch of nutmeg (optional)'
          ],
          steps: [
            'In a large saucepan, melt the butter over medium heat.',
            'Add the minced garlic and sauté for 1-2 minutes until fragrant.',
            'Add the spinach to the saucepan and stir until wilted, about 3-4 minutes.',
            'Reduce the heat to low and stir in the heavy cream and parmesan cheese.',
            'Cook for 5-7 minutes until the sauce has thickened and the spinach is coated in a creamy mixture.',
            'Season with salt and pepper to taste. If desired, add a pinch of nutmeg for extra flavor.',
            'Serve hot as a side dish or use as a topping for baked potatoes or grilled chicken.'
          ],
          duration: Duration(minutes: 25),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r24',
          title: 'Creamy Samp',
          description: 'Tender Beef stew',
          imageUrl: 'assets/csamp.jpg',
          ingredients: [
            '2 cups of dried samp (corn kernels), soaked overnight in water',
            '1 large onion, chopped',
            '2 garlic cloves, minced',
            '2 cups of chicken or vegetable broth',
            '2 cups of milk',
            '1/2 cup of heavy cream',
            '2 tbsp unsalted butter',
            'Salt and pepper to taste'
          ],
          steps: [
            'Drain the soaked samp and rinse with cold water.',
            'In a large saucepan, melt the butter over medium heat.',
            'Add the chopped onion and minced garlic and sauté for 2-3 minutes until fragrant.',
            'Add the drained samp to the saucepan and stir to coat in the butter mixture.',
            'Pour in the chicken or vegetable broth and bring to a simmer. Cover and cook for 1-1 1/2 hours until the samp is tender, stirring occasionally.',
            'Stir in the milk and heavy cream and continue cooking for another 15-20 minutes until the mixture has thickened and the samp is creamy.',
            'Season with salt and pepper to taste.',
            'Serve hot as a side dish, garnished with fresh herbs or chopped scallions if desired.'
          ],
          duration: Duration(minutes: 100),
          complexity: Complexity.Challenging,
          cost: 0.00),
      Recipe(
          id: 'r25',
          title: 'Lasagna',
          description:
              'a baked dish made with layers of wide pasta sheets, meat sauce, and cheese',
          imageUrl: 'assets/lasgna.jpeg',
          ingredients: [
            '1 pound ground beef',
            '1 large onion, chopped',
            '3 cloves garlic, minced',
            '2 cans (28 ounces each) of crushed tomatoes',
            '1 can (6 ounces) of tomato paste',
            '2 tablespoons of sugar',
            '2 teaspoons of salt',
            '1 teaspoon of dried basil',
            '1 teaspoon of dried oregano',
            '1/2 teaspoon of black pepper',
            '12 lasagna noodles',
            '4 cups of shredded mozzarella cheese',
            '1 1/2 cups of ricotta cheese',
            '1/2 cup of grated Parmesan cheese',
            '2 tablespoons of chopped fresh parsley'
          ],
          steps: [
            'In a large skillet, cook the ground beef over medium heat until browned. Drain off any excess fat.',
            'Add the chopped onion and minced garlic to the skillet and cook for 3-4 minutes until the onion is soft.',
            'Add the crushed tomatoes, tomato paste, sugar, salt, basil, oregano, and black pepper to the skillet. Stir to combine and bring to a simmer.',
            'Reduce the heat to low and let the sauce simmer for 20-30 minutes until it has thickened.',
            'While the sauce is simmering, cook the lasagna noodles according to package instructions. Drain and rinse under cold water.',
            'Preheat the oven to 375°F (190°C).',
            'In a bowl, mix together the ricotta cheese, 2 cups of shredded mozzarella cheese, and grated Parmesan cheese.',
            'Spread a thin layer of the meat sauce on the bottom of a 9x13 inch baking dish.',
            'Arrange a layer of lasagna noodles on top of the meat sauce.',
            'Spread a layer of the cheese mixture over the lasagna noodles.',
            'Repeat the layers of meat sauce, lasagna noodles, and cheese mixture until all the ingredients are used up. Top with the remaining shredded mozzarella cheese.',
            'Cover the baking dish with aluminum foil and bake in the preheated oven for 25-30 minutes.',
            'Remove the foil and continue baking for an additional 10-15 minutes until the cheese is golden brown and bubbly.',
            'Let the lasagna cool for 10-15 minutes before slicing and serving. Garnish with chopped fresh parsley if desired.'
          ],
          duration: Duration(minutes: 120),
          complexity: Complexity.Challenging,
          cost: 0.00),
      Recipe(
          id: 'r26',
          title: 'Caprese Salad',
          description:
              'a simple salad made with sliced fresh mozzarella, tomatoes, and basil leaves,',
          imageUrl: 'assets/capresesalad.jpg',
          ingredients: [
            '3-4 medium-sized ripe tomatoes, sliced',
            '8 ounces fresh mozzarella cheese, sliced',
            '1/4 cup fresh basil leaves',
            '2 tablespoons extra-virgin olive oil',
            '2 tablespoons balsamic vinegar',
            'Salt and black pepper, to taste'
          ],
          steps: [
            'Arrange the sliced tomatoes and mozzarella cheese on a serving platter, alternating them.',
            'Scatter the fresh basil leaves over the top of the tomato and mozzarella slices.',
            'Drizzle the olive oil and balsamic vinegar over the top of the salad.',
            'Season the salad with salt and black pepper to taste.',
            'Serve immediately and enjoy!',
            'You can also try variations of Caprese Salad, such as adding sliced avocados, prosciutto, or arugula. Enjoy this refreshing and delicious salad'
          ],
          duration: Duration(minutes: 5),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r27',
          title: 'Chiles Rellenos',
          description:
              'a dish made of roasted and stuffed chili peppers, usually with cheese or meat, and then battered and fried',
          imageUrl: 'assets/rellenos.jpg',
          ingredients: [
            '6 large poblano peppers',
            '8 oz. queso fresco cheese, crumbled',
            '2 tbsp. vegetable oil',
            '1/2 cup all-purpose flour',
            '4 large eggs, separated',
            '1/4 tsp. salt',
            '1 cup tomato sauce'
          ],
          steps: [
            'Preheat the broiler. Place the poblano peppers on a baking sheet and broil them, turning occasionally, until the skin is blistered and blackened on all sides, about 10-12 minutes.',
            'Transfer the peppers to a large bowl and cover them with a clean kitchen towel. Let them steam for 10-15 minutes to loosen the skin.',
            'Carefully peel off the skin of the peppers, then slit each one lengthwise down one side and remove the seeds and membranes.',
            'Stuff each pepper with the crumbled queso fresco cheese, being careful not to overstuff them.',
            'Heat the vegetable oil in a large skillet over medium-high heat.',
            'In a separate bowl, beat the egg whites until stiff peaks form. In another bowl, beat the egg yolks with the salt until thick and creamy.',
            'Gently fold the egg yolks into the beaten egg whites.',
            'Roll each stuffed pepper in the flour, shaking off any excess.',
            'Dip each pepper into the egg batter, making sure it is coated on all sides.',
            'Place the peppers in the hot oil and fry until golden brown and crispy, about 2-3 minutes per side.',
            'Remove the peppers from the skillet and drain them on a paper towel-lined plate.',
            'Serve the Chiles Rellenos hot, topped with tomato sauce. Enjoy!',
            'Note: you can also use different types of cheese or stuffing for the peppers, such as ground beef or chicken, or vegetables like corn, beans, or diced tomatoes.'
          ],
          duration: Duration(minutes: 45),
          complexity: Complexity.Challenging,
          cost: 0.00),
      Recipe(
          id: 'r28',
          title: 'Braaied Pork Chops',
          description: 'barbecue dish that is perfect for summertime grilling',
          imageUrl: 'assets/cpork.jpg',
          ingredients: [
            '4 pork chops, bone-in',
            '2 tablespoons olive oil',
            '2 cloves garlic, minced',
            '1 tablespoon lemon juice',
            '1 teaspoon dried thyme',
            'Salt and pepper, to taste'
          ],
          steps: [
            'In a small bowl, whisk together the olive oil, minced garlic, lemon juice, thyme, salt, and pepper.',
            'Rub the mixture all over the pork chops, making sure to coat them well.',
            'Cover the pork chops and let them marinate in the refrigerator for at least 30 minutes, or up to 8 hours.',
            'Preheat your grill to medium-high heat.',
            'Remove the pork chops from the marinade and shake off any excess. Discard the remaining marinade.',
            'Grill the pork chops for 5-6 minutes per side, or until they are cooked through and have grill marks on both sides.',
            'Remove the pork chops from the grill and let them rest for a few minutes before serving.',
            'Serve the Braaied Pork Chops hot with your favorite barbecue sides, such as corn on the cob or grilled vegetables'
          ],
          duration: Duration(minutes: 45),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r29',
          title: 'Pork ribs',
          description: 'sticky and delicious South African-style pork ribs',
          imageUrl: 'assets/rpork.jpeg',
          ingredients: [
            '2 racks of pork ribs',
            '1/2 cup brown sugar',
            '1/4 cup soy sauce',
            '1/4 cup honey',
            '2 tablespoons Worcestershire sauce',
            '2 tablespoons apple cider vinegar',
            '1 tablespoon smoked paprika',
            '1 tablespoon garlic powder',
            '1 tablespoon onion powder',
            'Salt and pepper, to taste'
          ],
          steps: [
            'Preheat your oven to 300°F (150°C).',
            'In a bowl, whisk together the brown sugar, soy sauce, honey, Worcestershire sauce, apple cider vinegar, smoked paprika, garlic powder, onion powder, salt, and pepper.',
            'Cut the racks of pork ribs in half, so that you have 4 smaller racks.',
            'Place the ribs in a large roasting pan and pour the sauce over them, making sure to coat them evenly.',
            'Cover the roasting pan with foil and bake in the preheated oven for 2-2.5 hours, or until the meat is tender and falls off the bone.',
            'Remove the ribs from the oven and preheat your grill to medium-high heat.',
            'Carefully transfer the ribs to the grill and brush with additional sauce. Grill for 5-6 minutes per side, or until the ribs are sticky and caramelized.',
            'Remove the ribs from the grill and let them rest for a few minutes before serving.',
            'Serve the ribs hot with additional sauce on the side.'
          ],
          duration: Duration(minutes: 180),
          complexity: Complexity.Challenging,
          cost: 0.00),
      Recipe(
          id: 'r30',
          title: 'Bobotie',
          description:
              'A spicy minced meat dish made with curried beef or lamb, topped with a savory egg custard',
          imageUrl: 'assets/bobotie.jpg',
          ingredients: [
            '1 kg ground beef or lamb',
            '2 onions, finely chopped',
            '3 cloves of garlic, minced',
            '2 slices of bread, soaked in 1 cup of milk',
            '1 Tbsp. curry powder',
            '1 tsp. turmeric',
            '1 tsp. ground cumin',
            '1 tsp. ground coriander',
            '2 Tbsp. apricot jam',
            '2 Tbsp. vinegar',
            '1 tsp. sugar',
            '1 bay leaf',
            '5 eggs',
            '1 1/2 cup of milk',
            'Salt and pepper to taste',
            'Butter or oil for frying'
          ],
          steps: [
            'Preheat the oven to 180°C (350°F).',
            'In a large skillet, fry the onions and garlic in the butter or oil until softened.',
            'Add the ground meat and cook until browned.',
            'Add the curry powder, turmeric, cumin, coriander, sugar, bay leaf, and salt and pepper to the skillet, and stir to combine.',
            'Add the soaked bread to the skillet and stir well to combine.',
            'Add the apricot jam and vinegar to the skillet and mix well.',
            'Transfer the meat mixture to a baking dish.',
            'In a separate bowl, whisk together the eggs and milk for the topping, and pour over the meat mixture.',
            'Bake the bobotie in the preheated oven for 40-45 minutes, until the topping is golden and set.',
            'Serve hot with yellow rice and a salad.'
          ],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r31',
          title: 'Bangers and Mash',
          description:
              'classic dish made with sausages (bangers) served with mashed potatoes and gravy',
          imageUrl: 'assets/bangers.jpg',
          ingredients: [
            '8 pork sausages (or any other kind of sausage you prefer)',
            '1 kg potatoes, peeled and chopped',
            '1/2 cup milk',
            '4 Tbsp. butter',
            'Salt and pepper to taste',
            '1 large onion, sliced',
            '2 Tbsp. olive oil',
            '1 Tbsp. all-purpose flour',
            '1 cup beef or chicken stock',
            '2 Tbsp. Worcestershire sauce'
          ],
          steps: [
            'Preheat the oven to 200°C (400°F).',
            'Place the sausages on a baking sheet and bake for 20-25 minutes until cooked through and golden brown.',
            'While the sausages are cooking, place the potatoes in a large pot of salted water and bring to a boil. Reduce the heat and simmer for 15-20 minutes, until the potatoes are tender.',
            'Drain the potatoes and mash them with the milk, butter, salt, and pepper until smooth and creamy.',
            'While the potatoes are cooking, heat the olive oil in a large skillet over medium heat.',
            'Add the sliced onion and cook for 5-7 minutes until softened and golden brown.',
            'Sprinkle the flour over the onions and stir well to combine.',
            'Pour in the stock and Worcestershire sauce and stir well to combine.',
            'Simmer the gravy for 5-10 minutes, until thickened.',
            'Serve the sausages on top of the mashed potatoes with the onion gravy spooned over the top.'
          ],
          duration: Duration(minutes: 60),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r32',
          title: 'Beef Wellington',
          description:
              'A gourmet dish made with a beef fillet wrapped in puff pastry and baked until golden',
          imageUrl: 'assets/Beef-Wellington.jpg',
          ingredients: [
            ' ',
            'Salt and pepper to taste',
            '2 Tbsp. olive oil',
            '1/2 cup finely chopped shallots',
            '4 cloves garlic, minced',
            '2 cups finely chopped mushrooms',
            '1/4 cup chopped fresh parsley',
            '2 Tbsp. Dijon mustard',
            '1/2 cup pâté (optional)',
            '1 package (450 g) puff pastry, thawed',
            '1 egg, beaten',
            'Flour for dusting'
          ],
          steps: [
            'Preheat the oven to 200°C (400°F).',
            'Season the beef fillet with salt and pepper on all sides.',
            'Heat the olive oil in a large skillet over high heat.',
            'Sear the beef fillet on all sides until browned, about 2-3 minutes per side.',
            'Remove the beef fillet from the skillet and set aside.',
            'In the same skillet, sauté the shallots and garlic over medium heat until softened, about 5-7 minutes.',
            'Add the chopped mushrooms and cook until they release their liquid and are lightly browned, about 10 minutes.',
            'Stir in the parsley and season with salt and pepper to taste.',
            'Spread the Dijon mustard over the beef fillet.',
            'Spread the mushroom mixture on top of the mustard.',
            'If using, spread the pâté on top of the mushroom mixture.',
            'Roll out the puff pastry on a floured surface into a large rectangle.',
            'Place the beef fillet in the center of the puff pastry.',
            'Fold the puff pastry over the beef fillet, tucking in the edges to seal.',
            'Brush the beaten egg over the top of the puff pastry.',
            'Place the beef Wellington on a baking sheet and bake for 30-40 minutes until the puff pastry is golden brown and crispy.',
            'Remove from the oven and let rest for 5-10 minutes before slicing.',
            'Serve your delicious Beef Wellington with your favorite side dishes such as roasted vegetables or mashed potatoes.'
          ],
          duration: Duration(minutes: 90),
          complexity: Complexity.Challenging,
          cost: 0.00),
      Recipe(
          id: 'r33',
          title: 'Nachos',
          description: 'Tender Beef stew',
          imageUrl: 'assets/nachos.jpg',
          ingredients: [
            '1 bag of tortilla chips',
            '1 cup of shredded cheese',
            '1/2 cup of diced tomatoes',
            '1/2 cup of diced onions',
            '1/2 cup of sliced jalapeños',
            '1/4 cup of sour cream',
            '1/4 cup of salsa'
          ],
          steps: [
            'Preheat the oven to 350°F (175°C).',
            'Spread the tortilla chips in a single layer on a baking sheet.',
            'Sprinkle the shredded cheese evenly over the tortilla chips.',
            'Add the diced tomatoes, onions, and jalapeños on top of the cheese.',
            'Bake the nachos in the oven for 8-10 minutes, or until the cheese is melted and bubbly.',
            'Remove the nachos from the oven and drizzle with sour cream and salsa.',
            'Serve immediately and enjoy',
            'You can also add other toppings like black beans, avocado, or shredded chicken, depending on your preference'
          ],
          duration: Duration(minutes: 20),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r34',
          title: 'crunchy chicken strips',
          description: 'crunchy and tasty chicken strips',
          imageUrl: 'assets/crispy.jpeg',
          ingredients: [
            '2 boneless, skinless chicken breasts, cut into strips',
            '1 cup of all-purpose flour',
            '2 teaspoons of garlic powder',
            '2 teaspoons of paprika',
            '1 teaspoon of salt',
            '1/2 teaspoon of black pepper',
            '2 eggs, beaten',
            '2 cups of panko breadcrumbs',
            'Cooking spray'
          ],
          steps: [
            'Preheat the oven to 400°F (200°C).',
            'In a bowl, mix together the flour, garlic powder, paprika, salt, and black pepper.',
            'In another bowl, beat the eggs.',
            'In a third bowl, place the panko breadcrumbs.',
            'Dip each chicken strip into the flour mixture, then into the egg mixture, and then into the panko breadcrumbs, making sure to coat evenly.',
            'Place the coated chicken strips on a baking sheet lined with parchment paper.',
            'Spray the chicken strips with cooking spray.',
            'Bake the chicken strips for 20-25 minutes, or until golden brown and crispy.',
            'Serve the chicken strips immediately with your favorite dipping sauce.'
          ],
          duration: Duration(minutes: 30),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r35',
          title: 'Jollof Rice',
          description:
              'A one-pot dish made with long-grain rice, tomatoes, peppers, onions, and spices',
          imageUrl: 'assets/Jollof-Rice.jpeg',
          ingredients: [
            '2 cups long-grain rice',
            '2 tbsp vegetable oil',
            '1 onion, diced',
            '1 red bell pepper, diced',
            '1 green bell pepper, diced',
            '3 garlic cloves, minced',
            '1 tsp grated ginger',
            '2 cups chicken or vegetable broth',
            '1 can (14.5 oz) diced tomatoes',
            '1 tsp smoked paprika',
            '1 tsp ground coriander',
            '1 tsp dried thyme',
            '1/2 tsp ground cinnamon',
            'Salt and pepper, to taste'
          ],
          steps: [
            'Rinse the rice several times in cold water until the water runs clear. Drain the rice and set aside.',
            'Heat the vegetable oil in a large pot over medium-high heat.',
            'Add the diced onions and bell peppers to the pot and sauté for about 5 minutes until the onions are translucent.',
            'Add the minced garlic and grated ginger to the pot and sauté for an additional 2-3 minutes until fragrant.',
            'Add the rinsed rice to the pot and stir to combine with the vegetables.',
            'Add the chicken or vegetable broth, canned tomatoes, smoked paprika, ground coriander, dried thyme, ground cinnamon, salt, and pepper to the pot. Stir to combine all the ingredients.',
            'Bring the mixture to a boil, then reduce the heat to low and cover the pot with a tight-fitting lid.',
            'Let the rice simmer for 20-25 minutes, or until the liquid is absorbed and the rice is tender.',
            'Fluff the rice with a fork and serve hot.'
          ],
          duration: Duration(minutes: 50),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r36',
          title: 'Schnitzel',
          description:
              'a thin, breaded and fried piece of meat (usually pork or veal) served with potatoes and salad',
          imageUrl: 'assets/Schnitzel.jpg',
          ingredients: [
            '4 thin slices of veal or pork cutlets, pounded to 1/4 inch thickness',
            '1/2 cup all-purpose flour',
            '2 large eggs',
            '1/2 cup breadcrumbs',
            'Salt and pepper',
            'Vegetable oil, for frying',
            'Lemon wedges, for serving'
          ],
          steps: [
            'Season the meat with salt and pepper on both sides.',
            'Place the flour in a shallow dish, beat the eggs in another shallow dish, and place the breadcrumbs in a third dish.',
            'Dip each slice of meat into the flour, shaking off any excess, then into the beaten eggs, and finally coat in the breadcrumbs, pressing the breadcrumbs onto the meat to help them adhere.',
            'Heat a large skillet over medium-high heat and add enough oil to coat the bottom of the pan.',
            'Once the oil is hot, carefully add the breaded meat to the pan, cooking 2-3 minutes per side until golden brown and crispy.',
            'Remove the cooked schnitzels to a paper towel-lined plate to drain any excess oil.',
            'Serve the schnitzel hot, garnished with lemon wedges.'
          ],
          duration: Duration(minutes: 30),
          complexity: Complexity.Simple,
          cost: 0.00),
      Recipe(
          id: 'r37',
          title: 'Spätzle',
          description:
              'a type of soft egg noodle, often served as a side dish with meat dishes or with cheese and fried onions',
          imageUrl: 'assets/Spätzle.jpeg',
          ingredients: [
            '2 cups all-purpose flour',
            '1 teaspoon salt',
            '1/2 teaspoon ground nutmeg',
            '4 large eggs',
            '1/2 cup milk or water',
            '4-6 quarts water',
            'Salt, for boiling',
            'Butter or olive oil, for serving'
          ],
          steps: [
            'In a large mixing bowl, whisk together the flour, salt, and nutmeg.',
            'In a separate bowl, beat together the eggs and milk or water until well combined.',
            'Gradually pour the egg mixture into the flour mixture, stirring with a wooden spoon until a thick, sticky batter forms.',
            'Bring a large pot of salted water to a boil.',
            'To form the Spätzle, use a Spätzle maker or a colander with large holes. Hold the tool over the boiling water and pour some of the batter through the holes into the water.',
            'Cook the Spätzle for 2-3 minutes or until they float to the surface of the water.',
            'Remove the cooked Spätzle with a slotted spoon and transfer them to a colander to drain.',
            'Repeat the process until all of the batter has been used.',
            'To serve, heat some butter or olive oil in a large skillet and add the cooked Spätzle. Sauté for a few minutes until lightly browned and heated through.',
            ' '
          ],
          duration: Duration(minutes: 45),
          complexity: Complexity.Simple,
          cost: 0.00),
    ];
  }
}
